const UserAnalytics = require('../models/UserAnalytics');
const { generateLLMResponse } = require('../utils/llmHelper');

/**
 * Adaptive Assessment Engine Service
 *
 * Generates adaptive questions using an LLM. It relies on the previous
 * responses from the database and the calculated analytics state to
 * dynamically tailor the interview difficulty and topic.
 */

// Simulated database interface for previous responses
// In a real implementation, you would require the UserResponse or similar model
// const AssessmentResponse = require('../models/AssessmentResponse');

/**
 * Fetches previous responses and creates the next adaptive question for a user.
 * 
 * @param {String} userId - The unique identifier of the user (ObjectId string)
 * @returns {Promise<String>} The adaptive question generated by the LLM
 */
const generateNextQuestion = async (userId) => {
    try {
        if (!userId) {
            throw new Error("userId is required to generate the next question.");
        }

        // 1. Read current analytics state from database
        const userAnalytics = await UserAnalytics.findOne({ userId });

        if (!userAnalytics) {
            throw new Error("Analytics profile not found. Unable to generate an adaptive question.");
        }

        // 2. Read previous responses from database
        // Assuming we have a mock query or a real one to get past answers
        // Simulated: const pastResponses = await AssessmentResponse.find({ userId });
        const pastResponses = []; // Mocked empty for now as no schema was provided for this
        const historyText = pastResponses.length > 0
            ? pastResponses.map((r, i) => `Q${i + 1}: ${r.question} | Ans: ${r.answer}`).join("\n")
            : "No previous responses yet (First question).";

        // 3. Extract analytics data
        // Convert the Map to a plain object string for the prompt
        let interestVectorStr = "None";
        if (userAnalytics.interestVector && userAnalytics.interestVector.size > 0) {
            const tempObj = {};
            userAnalytics.interestVector.forEach((value, key) => { tempObj[key] = value });
            interestVectorStr = JSON.stringify(tempObj);
        }

        const cognitiveProfile = userAnalytics.cognitiveProfile || "Unknown";
        const performanceScoreStr = `Passion/Confidence: ${userAnalytics.passionScore}/${userAnalytics.confidenceScore}`;

        // 4. Create a structured prompt
        const systemInstruction = `
You are an expert academic advisor and assessor.
Your goal is to evaluate a student's technical interests and aptitude without being monotonous.

CRITICAL INSTRUCTIONS:
- Generate exactly ONE scenario-based question.
- Avoid repeating topics from the user's history.
- Ensure the difficulty increases slightly if the user's performance/score looks high, or decreases if low.
- Keep the generated question under 120 words.
- Maintain a warm, conversational, yet professional tone.
- Directly ask the question without extra introductory fluff like "Sure, here is the question" or "Based on your history".

Context mapping:
If the user shows High Logical cognitive profile, lean towards algorithms, problem-solving, and architecture.
If the user shows High Creative cognitive profile, lean towards UI/UX, product design, and frontend workflows.
`;

        const userContextPrompt = `
User Context & State:
---------------------
Previous Interactions/History: 
${historyText}

Current Domain Interests Profile:
${interestVectorStr}

Cognitive Profile Trait:
${cognitiveProfile}

Performance & Engagement Score:
${performanceScoreStr}

Based strictly on this context, generate the next optimal, adaptive question to further evaluate their academic direction. Remember to enforce the word count and be conversational.
`;

        // 5. Call LLM
        const nextQuestion = await generateLLMResponse(systemInstruction, userContextPrompt);

        // 6. Return the strictly formatted question
        if (!nextQuestion || nextQuestion.trim() === "") {
            throw new Error("Received an empty response from the LLM engine.");
        }

        return nextQuestion.trim();

    } catch (error) {
        console.error(`[AdaptiveAssessmentEngine Error]: Failed to generate next question for user ${userId}`, error);
        throw error;
    }
};

module.exports = {
    generateNextQuestion
};
